### ISSUE TITLE
Unit system mismatch

### ISSUE THREAD

**Issue by kamiKAC** [chaunceygardiner/weewx-loopdata#1]
I'm using weewx since two years. Now I'm tying to get weather data from my PWS into OpenHAB using JSON.
I've installed weewx-loopdata extension and configured paths to local file. All other setting left default.
Extension does not create file complaining "Unit system mismatch"
I live in Europe so my reports are generated in metric units.

```
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: Service version is 1.0.
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: LoopData file is: /var/www/h######k.me/public_html/loop-data.txt
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: archive_interval   : 300
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: loop_data_dir      : /var/www/h######k.me/public_html/
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: filename           : loop-data.txt
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: target_report      : StandardReport
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: fields_to_include  : ['dateTime', 'windSpeed', 'COMPASS_windDir', 'DESC_barometerRate', 'FMT_barometer', 'FMT_day_rain_total', 'FMT_dewpoint', 'FMT_heatindex', 'FMT_outHumidity', 'FMT_outTemp', 'FMT_rain', 'FMT_rainRate', 'FMT_windchill', 'FMT_windSpeed', 'FMT_HI_windGust', 'FMT_10mMaxGust']
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: fields_to_rename   : {}
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: tmpname            : /tmp/LoopData_bjjam9o
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: enable             : 0
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: remote_server      : www.foobar.com
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: remote_port        : None
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: remote_user        : root
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: remote_dir         : /home/weewx/loop-data
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: compress           : 0
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: log_success        : 0
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: ssh_options        : -o ConnectTimeout=1
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: timeout            : 1
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: skip_if_older_than : 3
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: barometer_rate_secs: 10800
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: wind_rose_secs     : 86400
Jun 27 00:56:53 Helios weewx[9287] INFO user.loopdata: wind_rose_points   : 16
Jun 27 00:56:53 Helios weewx[9287] INFO __main__: Starting up weewx version 4.1.1
Jun 27 00:56:53 Helios weewx[9287] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jun 27 00:56:53 Helios weewx[9287] INFO weewx.manager: Starting backfill of daily summaries
Jun 27 00:56:53 Helios weewx[9287] INFO weewx.engine: Starting main packet loop.
Jun 27 00:57:13 Helios weewx[9287] INFO user.interceptor: skipping rain measurement of 7.78: no last rain
Jun 27 00:57:13 Helios weewx[9287] INFO user.loopdata: LoopData process queue took 0.019754 seconds to set up.
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****  Traceback (most recent call last):
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****    File "/usr/share/weewx/user/loopdata.py", line 390, in process_queue
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****      self.day_summary.addRecord(pkt)
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****    File "/usr/share/weewx/weewx/accum.py", line 429, in addRecord
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****      func(self, record, obs_type, add_hilo, weight)
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****    File "/usr/share/weewx/weewx/accum.py", line 518, in check_units
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****      self._check_units(record['usUnits'])
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****    File "/usr/share/weewx/weewx/accum.py", line 603, in _check_units
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****      raise ValueError("Unit system mismatch %d v. %d" % (self.unit_system,
Jun 27 00:57:13 Helios weewx[9287] CRITICAL user.loopdata:     ****  ValueError: Unit system mismatch 16 v. 1

```

**Comment by chaunceygardiner** [comment]
I have reproduced this error.  I’ll look into fixing it today or tomorrow.

Thanks for reporting it.

**Comment by chaunceygardiner** [comment]
I’ve updated the extension to v 1.1.  I tested it with a Metric database and also with Metric reports.

Thanks again for reporting this and please let me know If you have any other issues.

Cheers,
John

**Comment by kamiKAC** [comment]
Dear John

Thanks for the quick fix :)

Now I'm able to get loop-data.txt file but seems there is still something wrong:
Config:
 ```
[[Include]]
        fields = dateTime, windSpeed, COMPASS_windDir, DESC_barometerRate, barometer, day_rain_total, dewpoint, heatindex, outHumidity, outTemp, appTemp, rain, rainRate, windchill, windSpeed, windGust, inTemp
```

File output:
```
{"dateTime": 1593383704, "windSpeed": "2", "COMPASS_windDir": "WNW", "DESC_barometerRate": "Rising Slowly", "barometer": "1013.9", "dewpoint": "18.0", "heatindex": "19.3", "outHumidity": "92", "outTemp": "19.3", "appTemp": "21.6", "rain": "0.0", "rainRate": "0.0", "windchill": "19.3", "windGust": "4", "inTemp": "25.0"}
```

As rain could be wrong reported from the PWS "rain": "0.0" I'm not sure if there is something wrong here. HTML file generated every 5 minutes shows daily rain 0,3mm at the moment.
Strange thing is "day_rain_total" is completely missing in output file.

Best regards
Marcin

**Comment by chaunceygardiner** [comment]
Also, please re-read this part of the readme to get a list of all available fields.

This section lists some likely fields. In reality, LoopData runs through the daily summaries and includes all observations it finds. The daily summaries also conveniently privide day high (HI_) and day low (LO_) observations.

In addition to these observations, LoopData also tracks 10 min. max gust, barometer rate and windrose data.

When no fields are specified, all fields will written to loop-data.txt. Thus, to get a full list of fields, comment out the fields line in the LoopData section of weewx.conf. Next, look in the loop-data.txt file to find all of the available fields.

**Comment by chaunceygardiner** [comment]
It seems I never sent this:
Sending now, but also will send a follow-up.
 ﻿
The rain reported is the rain recorded in that loop.  For instance, I get loop packets every 2s, so the rain reported is the rain that fell in the last 2 seconds.

day_rain_total is much more interesting to show.  I suspect it is not in the loop packet.  Would you please send loop packets for your station?

**Comment by chaunceygardiner** [comment]
Good news.  I have the day accumulators.  That’s how I’m sending the day lows and highs.

The accumulators also provide sum, count, weighted sum and sum time.

I’ll add these.  The equivalent to day_rain_total (which, I assume, your driver does not send in the loop) would be SUM_rain or WSUM_rain (they should both yield the same value).

I’ll add this and update the readme.

Cheers,
John

**Comment by chaunceygardiner** [comment]
OK, I pushed 1.2.2.

I just added sum for now.  SUM_rain will give you what you want.  If you want it formatted with units, use FMT_SUM_rain.

SUM_<obs> : The sum of the observation values reported today. SUM_rain is especially useful for reporting the day's rain.
FMT_SUM_<obs> : The sum of the observation values reported today. It is formatted and includes units (e.g., 0.42 in).

**Comment by chaunceygardiner** [comment]
BTW, this bug was about unit system mismatch.  We’ll leave this open so I can get feedback on the SUM I’ve just added; but, in the future, please open a new issue when you have a new issue.

**Comment by chaunceygardiner** [comment]
loopdata v1.3 has been pushed with average and weighted average of scalar observations.
Closing this issue.  Please open a new issue if you find anything that isn’t working as advertised.

AVG_<obs> : The average of the observation values reported today.

FMT_AVG_<obs> : The average of the observation values reported today. It is formatted and includes units (e.g., 3.4 mph).

WAVG_<obs> : The weighted average of the observation values reported today.

FMT_WAVG_<obs> : The weighted average of the observation values reported today. It is formatted and includes units (e.g., 3.4 mph).
