### ISSUE TITLE
Install fail Weewx v5.0rc3

### ISSUE THREAD

**Issue by JonFear** [chaunceygardiner/weewx-loopdata#11]
Hi

No surprise but failed to install for v5rc3. Any chance you can take a look and get working? It is a nice clean way of displaying simply the loop data..!

Thanks

Jon

`jon@weewx-v5:~$ sudo weectl extension install https://github.com/chaunceygardiner/weewx-loopdata/releases/download/v3.3.2/weewx-loopdata-3.3.2.zip
sudo: unable to resolve host weewx-v5.local: Name or service not known
Using configuration file /etc/weewx/weewx.conf
Install extension 'https://github.com/chaunceygardiner/weewx-loopdata/releases/download/v3.3.2/weewx-loopdata-3.3.2.zip' (y/n)? y
Extracting from tar archive /tmp/tmp90g4sr43
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 122, in install_extension
    extension_name = self._install_from_file(test_fd.name, info.get_content_subtype())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 153, in _install_from_file
    member_names = weecfg.extract_tar(filepath, dir_name, self.printer)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 665, in extract_tar
    with tarfile.open(filename, mode='r') as tar_archive:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 1639, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')`

**Comment by chaunceygardiner** [comment]
Hi Jon,

As  tkeffer points out when also raised the issue on weewx:
“Flaw with WeeWX (not the extension).“

BTW, from your reply, I don’t think you understood Tom’s reply.  It’s an issue with WeeWX itself.  It is not recognizing the zip file and trying to treat it as a gripped tar file.

As such, I’ll close this issue; but I should point out that I have yet to install WeeWX 5.0.  I’m waiting for most of the issues to be worked out.  When I do install it, rest assured that I will get loopdata running on 5.0.  I very much depend on this plugin.

**Comment by chaunceygardiner** [comment]
I had a chance to install WeeWX 5.0 with the pip method.  Since I used the pip method, I needed to install the prerequisite sortedcontainers with:
pip install sortedcontainers

The extension works under 5.0 with no changes.
