### ISSUE TITLE
Max/Min dateTime

### ISSUE THREAD

**Issue by okjohn** [chaunceygardiner/weewx-loopdata#4]
Thanks for writing this.  Works great!

I would like the dateTime values for when the daily/monthy/annual max/min temperature and wind values occur.  Any hope of adding these values to the output?  

Thanks!

**Comment by chaunceygardiner** [comment]
All of these are already available.  For example, the min/max daily temperature is:
$day.outTemp.mintime 
$day.outTemp.maxtime

Do you mean you would like me to add them to the sample report?

**Comment by okjohn** [comment]
Yep.  My mistake.  I added those variables to weewx.conf and it works fine.

I am sorry to have wasted your time.  Love the code.
