### ISSUE TITLE
weewx-loopdata-2.9.zip not available in GitHub

### ISSUE THREAD

**Issue by ar0berts** [chaunceygardiner/weewx-loopdata#7]
Hi John,
The weewx-loopdata-master.zip throws an error on 
`andrew@Weather-Centre:~/weather-station$ sudo /usr/share/weewx/wee_extension --install weewx-loopdata-master.zip
[sudo] password for andrew: 
/usr/bin/env: ‘python’: No such file or directory
`
which I fixed on Ubuntu 20.04 with:
`sudo apt-get install python-is-python3`

but now, I get tripped up on 
`andrew@Weather-Centre:/usr/bin$ sudo /usr/share/weewx/wee_extension --install weewx-loopdata-master.zip
Request to install 'weewx-loopdata-master.zip'
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 92, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 84, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 139, in install_extension
    raise InstallError("Extension '%s' not found." % extension_path)
weecfg.extension.InstallError: Extension 'weewx-loopdata-master.zip' not found.
`
Could you make weewx-loopdata-2.9.zip available?

Sorry if this is a newbie question, but as Chance says, "there will be growth in the spring."

Andrew

**Comment by chaunceygardiner** [comment]
Hi Andrew,

I appreciate the Chauncey Gardiner quote.  I think most people just assume my name is Chauncey Gardiner.

wee_extension is clearly not finding weewx-loopdata-master.zip.  With the way you typed the command, weewx-loopdata-master.zip Would have to be in the current directory.  If it isn’t, you’ll need to enter the full path of weewx-loopdata-master.zip.

As for making weewx-loopdata-2.9.zip available on github, it is available.  Click on latest (in the releases section), and look for it under assets (it’s the first item).

**Comment by ar0berts** [comment]
So it is! - Peripheral vision deficit disorder as the Domestic Goddess describes it. Installs perfectly.
Thanks John.
