### ISSUE TITLE
Alltime Data

### ISSUE THREAD

**Issue by Millardiang** [chaunceygardiner/weewx-loopdata#9]
I really think this is an excellent extension. Is there any chance that you will be able to include alltime data in a future update? I have attempted to adapt your code to do that myself but failed miserably.

**Comment by chaunceygardiner** [comment]
Yes, there is a chance since all time is a simpler case (as I wouldn’t have to keep track of removing observations when they expired (i.e., when they no longer fall within the rolling timeframe).

**Comment by chaunceygardiner** [comment]
@Millardiang I added support for an alltime tag and released version 3.1 with alltime included.

**Comment by Millardiang** [comment]
Wow that’s what I call service. Thank you very much. I will study it closely to see where I failed:-)Sent from my iPhoneOn 19 Nov 2022, at 19:03, John Kline ***@***.***> wrote:﻿
@Millardiang I added support for an alltime tag and released version 3.1 with alltime included.

Update
alltime data flowing perfectly.
Thank you
